services:
  app:
    build: .
    container_name: hello_node
    expose:
      - "3000"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hello_node.rule=Host(`bosnam.com`)"
      - "traefik.http.routers.hello_node.entrypoints=websecure"
      - "traefik.http.routers.hello_node.tls.certresolver=letsencrypt"
      - "traefik.http.services.hello_node.loadbalancer.server.port=3000"
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
